services:

  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.email=your-email@example.com
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    networks:
      - Prophecy-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    # image: ip/makrotos/prophecy:latest
    restart: unless-stopped
    pull_policy: always
    container_name: frontend
    environment:
      - NODE_ENV=production
    networks:
      - Prophecy-network
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`your-domain.com`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - Prophecy-network

  frontend-dev-Prophecy:
    image: node:lts-alpine
    container_name: frontend-dev-Prophecy
    command: sh -c "npm install debug@4.3.4 && npm ci --include=dev && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    working_dir: /app
    volumes:
      - ./Frontend:/app
      - ./Frontend/tmp:/app/tmp
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - Prophecy-network
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend-prophecy
    restart: unless-stopped
    pull_policy: always
    environment:
      - SERVER_PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_INTERNAL_PORT=5432
      - DB_USER=example_user
      - DB_PASSWORD=example_password
      - DB_NAME=example_db
      - JWT_SECRET=example_jwt_secret
      - TELEGRAM_BOT_TOKEN=2201417632:AAHkv8Ta_qSAHBDQs-B81VVMGIUVqQa053c
      - ADMIN_TELEGRAM_ID=2202931663
    networks:
      - Prophecy-network
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: postgres-prophecy
    restart: unless-stopped
    environment:
      - POSTGRES_DB=example_db
      - POSTGRES_USER=example_user
      - POSTGRES_PASSWORD=example_password
    ports:
      - "5432:5432"
    networks:
      - Prophecy-network
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  Prophecy-network:
    driver: bridge

volumes:
  pgdata: