services:

  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=admin@example.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    networks:
      - Prophecy-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    # image: ip/makrotos/prophecy:latest
    restart: unless-stopped
    pull_policy: always
    container_name: frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`prophecy.example.com`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.frontend.service=frontend-service"
      - "traefik.http.services.frontend-service.loadbalancer.server.port=80"
      - "traefik.http.routers.frontend-http.rule=Host(`prophecy.example.com`)"
      - "traefik.http.routers.frontend-http.entrypoints=web"
      - "traefik.http.routers.frontend-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    environment:
      - NODE_ENV=production
      - DOMAIN=prophecy.example.com
    networks:
      - Prophecy-network
    depends_on:
      - backend

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - Prophecy-network

  frontend-dev-Prophecy:
    image: node:lts-alpine
    container_name: frontend-dev-Prophecy
    command: sh -c "npm install debug@4.3.4 && npm ci --include=dev && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    working_dir: /app
    volumes:
      - ./Frontend:/app
      - ./Frontend/tmp:/app/tmp
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - Prophecy-network
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend-prophecy
    restart: unless-stopped
    pull_policy: always
    environment:
      - SERVER_PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_INTERNAL_PORT=5432
      - DB_USER=prophecy_user
      - DB_PASSWORD=prophecy_password
      - DB_NAME=prophecy_db
      - JWT_SECRET=prophecy_jwt_secret_key_change_in_production
      - TELEGRAM_BOT_TOKEN=1234567890:ABC_DEF_GHI_JKL_MNO_PQR_STU
    # - ADMIN_TELEGRAM_ID=123456789
    networks:
      - Prophecy-network
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: postgres-prophecy
    restart: unless-stopped
    environment:
      - POSTGRES_DB=prophecy_db
      - POSTGRES_USER=prophecy_user
      - POSTGRES_PASSWORD=prophecy_password
    ports:
      - "5432:5432"
    networks:
      - Prophecy-network
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  Prophecy-network:
    driver: bridge

volumes:
  pgdata: