name: Backend Docker CI

on:
  push:
    branches: ["main"]
    paths:
      - "Backend/**"
      - ".github/workflows/backend-docker.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "Backend/**"
  workflow_dispatch:

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'push' || github.event_name == 'workflow_dispatch') &&
      !contains(github.event.head_commit.modified, 'Frontend/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Allow insecure registry
        run: |
          echo '{ "insecure-registries":["${{ secrets.REGISTRY_URL }}"] }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Private Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build Docker image
        run: |
          cd Backend
          docker build -t ${{ secrets.REGISTRY_URL }}/makrotos/prophecy-backend:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.REGISTRY_URL }}/makrotos/prophecy-backend:latest

  test-backend:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request' &&
      !contains(github.event.pull_request.head.sha, 'Frontend/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Backend Docker image (test)
        run: |
          cd Backend
          docker build -t prophecy-backend:test .
