name: Backend Docker CI

on:
  push:
    branches: ["main"]
    paths:
      - "Backend/**"
      - ".github/workflows/backend-docker.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "Backend/**"
  workflow_dispatch:

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'push' || github.event_name == 'workflow_dispatch') &&
      !contains(github.event.head_commit.modified, 'Frontend/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Получаем всю историю коммитов для получения списка изменений

      - name: Allow insecure registry
        run: |
          echo '{ "insecure-registries":["${{ secrets.REGISTRY_URL }}"] }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Private Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build Docker image
        run: |
          cd Backend
          docker build -t ${{ secrets.REGISTRY_URL }}/makrotos/prophecy-backend:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.REGISTRY_URL }}/makrotos/prophecy-backend:latest

      - name: Get commit history
        id: commits
        run: |
          # Получаем коммиты с предыдущего пуша до текущего
          if [ "${{ github.event.before }}" != "0000000000000000000000000000000000000000" ]; then
            COMMITS=$(git log --oneline --no-decorate ${{ github.event.before }}..${{ github.event.after }} --format="• %s (%h)" | sed 's/"/\\"/g')
          else
            # Для первого коммита в репозитории или workflow_dispatch
            COMMITS=$(git log --oneline --no-decorate -10 --format="• %s (%h)" | sed 's/"/\\"/g')
          fi
          
          # Экранируем специальные символы для JSON
          COMMITS_ESCAPED=$(echo "$COMMITS" | python3 -c "import sys,json; print(json.dumps(sys.stdin.read()))")
          echo "commits_list<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMITS_ESCAPED" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send Telegram notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            🚀 **Backend обновлён!**
            
            📋 **Последние коммиты:**
            ${{ fromJSON(steps.commits.outputs.commits_list) }}
            
