name: Backend Docker CI

on:
  push:
    branches: ["main"]
    paths:
      - "Backend/**"
      - ".github/workflows/backend-docker.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "Backend/**"
  workflow_dispatch:

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:buildx-stable-1
          buildkitd-flags: --allow-insecure-entitlement security.insecure

      - name: Configure insecure registry
        run: |
          echo '{"insecure-registries": ["${{ secrets.REGISTRY_URL }}"]}' | sudo tee /etc/docker/daemon.json
          sudo systemctl reload docker
          sleep 5

      - name: Login to Private Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./Backend
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/makrotos/prophecy-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          insecure: true
          allow: security.insecure

  test-backend:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Backend Docker image (test)
        uses: docker/build-push-action@v4
        with:
          context: ./Backend
          tags: prophecy-backend:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
