name: Frontend Docker CI

on:
  push:
    branches: ["main"]
    paths:
      - "Frontend/**"
      - ".github/workflows/frontend-docker.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "Frontend/**"
  workflow_dispatch:

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'push' || github.event_name == 'workflow_dispatch') &&
      !contains(github.event.head_commit.message, 'Backend/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Allow insecure registry
        run: |
          echo '{ "insecure-registries":["${{ secrets.REGISTRY_URL }}"] }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Private Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build Docker image
        run: |
          cd Frontend
          docker build --target prod -t ${{ secrets.REGISTRY_URL }}/makrotos/prophecy-frontend:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.REGISTRY_URL }}/makrotos/prophecy-frontend:latest

  test-frontend:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request' &&
      !contains(github.event.pull_request.head.sha, 'Backend/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Frontend Docker image (test)
        run: |
          cd Frontend
          docker build --target prod -t prophecy-frontend:test .
